name: Release Package

on:
  workflow_dispatch: # 手动触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 源码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 Node.js 并启用 Corepack
      - name: Setup Node.js and enable Corepack
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: corepack enable

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4️⃣ 运行 release 脚本
      - name: Run release script
        run: pnpm release

      # 5️⃣ 上传打包好的 zip 文件为 artifact
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: |
            ./$(node -p "const t=require('./src/theme.ts').themeVersion; t.name + '-' + t.version + '-' + t.type + '.zip'")
